### ISSUE TITLE
SyntaxError: 'return' with argument inside generator

### ISSUE THREAD

**Issue by torbjornvatn** [matumaros/pypedrive#6]
I tried to test the library, but ran into this error:

``` python
Traceback (most recent call last):
  File "hepp.py", line 1, in <module>
    from pypedriver import Client
  File "/usr/local/lib/python2.7/site-packages/pypedriver/__init__.py", line 21, in <module>
    from .client import Client
  File "/usr/local/lib/python2.7/site-packages/pypedriver/client.py", line 5, in <module>
    from .model import Model
  File "/usr/local/lib/python2.7/site-packages/pypedriver/model.py", line 195
    yield getattr(self.__client, self.__name)(**data)
SyntaxError: 'return' with argument inside generator
```

**Comment by matumaros** [comment]
I didn't test it with Python 2 yet, only with 3. I am sorry that I did not specify that in the readme, I have added that now. Right now I am very busy with other things, which makes support for Python 2.x not a priority. So if you know how to fix the issue, please contribute and make a pull request.

**Comment by torbjornvatn** [comment]
Ok, we're using Python 2.7 for historical reasons and I'm not fluent enough in Python to try to make a fix I'm afraid.
